config/routes.rb
MixMes::Application.routes.draw do
  resources :messages

  root 'static_pages#home'

  get 'auth/:provider/callback' => "sessions#create"

  delete '/signout' => "sessions#destroy"

end

app/models/graph_api.rb
class	GraphAPI
	include HTTParty

	base_uri "api.mixi-platform.com/2"

	def self.get_received_messages(user)
		get("/messages/@me/@inbox", headers: auth_header(user)).parsed_response
	end

	def self.get_sent_messages(user)
		get("/messages/@me/@outbox", headers: auth_header(user)).parsed_response
	end

	def self.auth_header(user)
		{ 'Authorization' => "Bearer #{user.access_token}" }
	end
end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :user

	def self.get_messages(user)
		messages = GraphAPI.get_received_messages(user)
		messages["Entry"].each do |message|
			user.messages.build(mid: message["id"],
				                  time_sent: message["time_sent"],
				                  body: GraphAPI.get_message_body(message["id"]),
				                  conversant_id: message["sender"]["id"])
		end
	end


	def last_update(user)
		user.messages.last.created_at || ""
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_uniqueness_of :uid, :scope => [:provider]

	has_many :messages

	before_create { generate_token(:remember_token) }

	def self.create_with_omniauth(auth_hash)
		create! do |user|
			user.provider = auth_hash["provider"]
			user.uid = auth_hash["uid"]
			user.name = auth_hash["info"]["name"]
		end
	end

	def self.new_token
		SecureRandom.urlsafe_base64
	end

	def self.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def generate_token(column)
		begin
			self[column] = User.encrypt(User.new_token)
		end while User.exists?(column => self[column])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_filter :signed_in_user

	def index
		response = GraphAPI.get_received_messages(current_user)
		@messages = response["entry"]
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || 
		       User.create_with_omniauth(auth_hash)
		sign_in user, auth_hash
		redirect_to root_url 
	end

	def destroy
		sign_out
		redirect_to root_url
	end

	protected

	def auth_hash
		request.env["omniauth.auth"]
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Accepts user and OmniAuth hash as arguments
	def sign_in(user, auth_hash)
		remember_token = User.new_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attributes(remember_token: User.encrypt(remember_token),
			                     access_token: auth_hash["credentials"]["token"],
			                     refresh_token: auth_hash["credentials"]["refresh_token"])
		self.current_user = user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user
		remember_token = cookies[:remember_token]
		@current_user ||= User.find_by(remember_token: User.encrypt(remember_token))
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		redirect_to root_path unless signed_in?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
			</button>
			<%= link_to "MixMes", "#", class: "navbar-brand" %>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Messages", messages_path %></li>
				<li><%= link_to "Friends", "#" %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= current_user.name %><b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", "#" %></li>
							<li><%= link_to "Settings", "#" %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign Out", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Sign In", 'auth/mixi' %></li>
				<% end %>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>
	<%= render "layouts/navbar" %>
	<div class="container-fluid">
		<% flash.each do |key, value| %>
			<%= content_tag :div, value, class: "alert alert-#{key}" %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/messages/index.html.erb
<div class="container-fluid">
		<div class="span10 offset2">
			<% @messages.each do |message| %>
				<div>
					<h2><%= link_to message["title"], message["sender"]["id"] %></h2>
				</div>
			<% end %>
		</div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid">
	<% if signed_in? %>
		<div class="row">
			<h1>You're signed in, homie</h1>
		</div>
	<% else %>
	<div class="jumbotron center">
		<h1>MixMes</h1>
		<h2>The simple mixi messenger</h2>
		<%= link_to image_tag('/m_balloon_icon.png', size: "100"),'auth/mixi' %>
	</div>
	<% end %>
</div>

app/views/static_pages/home.html.haml
.row-fluid
	.hero-unit.center
		.span8.offset2
			%h1 MixMes
			%h2 The simple mixi messenger
			=link_to image_tag('/m_balloon_icon.png', size: "100"),'auth/mixi'